# Generated by Django 4.1.2 on 2022-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_rating_author_authorrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editTime',
            field=models.DateTimeField(null=True),
        ),
    ]
