# Generated by Django 4.1.2 on 2023-01-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_name_en_category_name_ru_post_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentType_en',
            field=models.CharField(choices=[('news', 'новость'), ('post', 'статья')], default='post', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType_ru',
            field=models.CharField(choices=[('news', 'новость'), ('post', 'статья')], default='post', max_length=4, null=True),
        ),
    ]
