# Generated by Django 4.1.2 on 2023-01-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_contenttype_en_post_contenttype_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentType_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentType_ru',
        ),
    ]
